config/routes.rb
Rails.application.routes.draw do

	resources :costs do
	  collection { post :import }
	end
	resources :data_importer, only: [:index, :create]

  root 'costs#index'

end

app/models/attachment.rb
class Attachment
  DIR = 'public/attachments'
  attr_reader :file

  def initialize(uploaded_file)
    @uploaded_file = uploaded_file
  end

  def create
    Dir.mkdir Attachment::DIR unless Dir.exist? Attachment::DIR
    @file = Rails.root.join(Attachment::DIR, @uploaded_file.original_filename + '-' + Time.new.to_formatted_s(:number))
    File.open(@file, 'wb') do |file|
      file.write(@uploaded_file.read)
    end
  end
end

app/models/cost.rb
class Cost < ActiveRecord::Base

def self.import(file)
  spreadsheet = open_spreadsheet(file)
  header = spreadsheet.row(1)
  (2..spreadsheet.last_row).each do |i|
    row = Hash[[header, spreadsheet.row(i)].transpose]
    cost = find_by_id(row["id"]) || new
    cost.attributes = row.to_hash.slice(*accessible_attributes)
    cost.save!
  end
end

# def self.import(file)
#     file.readlines.each_with_index do |line, index|
#       next if index.zero?
#       lines = line.split(/\t/)
#       create! do |po|
#         po.purchaser_name   = lines[0]
#         po.item_description = lines[1]
#         po.item_price       = lines[2].to_f
#         po.purchase_count   = lines[3].to_i
#         po.merchant_address = lines[4]
#         po.merchant_name    = lines[5]
#       end
#     end
#   end

def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".tab" then Csv.new(file.path, nil, :ignore)
  else raise "Unknown file type: #{file.original_filename}"
  end
end

end

app/models/data_importer.rb
require 'csv'

class DataImporter < ActiveRecord::Base

  class << self
    def import(filepath)
      total_amount_gross_revenue = BigDecimal.new("0")
      CSV.foreach(filepath, headers: true, header_converters: :symbol, converters: :numeric, col_sep: "\t") do |row|
        row_total_amount_gross_revenue = import_row(row)
        total_amount_gross_revenue += row_total_amount_gross_revenue
      end
      total_amount_gross_revenue
    end

    private

    def import_row(row)
      row_total_amount_gross_revenue = BigDecimal.new("0")
      DataImporter.transaction do
        purchaser = Purchaser.find_or_create_by(name: row[:purchaser_name])
        merchant = Merchant.find_or_create_by(name: row[:merchant_name], address: row[:merchant_address])
        item = Item.find_or_create_by(description: row[:item_description], price: row[:item_price], merchant_id: merchant.id)
        # always create a new purchase row, assuming a purchaser can buy the same item across multiple purchases
        purchase = Purchase.create(count: row[:purchase_count], item_id: item.id, purchaser_id: purchaser.id)
        row_total_amount_gross_revenue = calculate_row_total_amount_gross_revenue(purchase.count, item.price)
      end
      row_total_amount_gross_revenue
    end

    def calculate_row_total_amount_gross_revenue(purchase_count, item_price)
      purchase_count*item_price
    end
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :description, :price, :merchant_id, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  belongs_to :merchant
  has_many :purchases
end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  validates :name, :address, presence: true
  has_many :items
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  validates :count, :purchaser_id, :item_id, presence: true
  validates :count, numericality: {greater_than_or_equal_to: 1}
  belongs_to :purchaser
  belongs_to :item
end

app/models/purchaser.rb
class Purchaser < ActiveRecord::Base
  validates :name, presence: true
  has_many :purchases
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]
  #respond_to :json

	def import
	  Cost.import(params[:file])
	  redirect_to root_url, notice: "Products imported."
	end

  # GET /costs
  # GET /costs.json
  def index
  	#respond_with PurchaseOrder.all
    @costs = Cost.all
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params)

    respond_to do |format|
      if @cost.save
        format.html { redirect_to @cost, notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end

    begin
      total_amount_gross_revenue = DataImporter.import(params['purchases_file'].path)
      redirect_to action: index, notice: "File was successfully imported. Total amount gross revenue: #{view_context.number_to_currency(total_amount_gross_revenue)}"
    rescue Exception => e
      logger.error "!!! Import failed. Error: #{e.message}"
      redirect_to action: index, error: 'Import failed. Please make sure your file is properly formatted.'
    end

  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

 def upload
    attachment = Attachment.new(params[:upload])
    attachment.create
    PurchaseOrder.import(attachment.file)
    render nothing: true, status: 200
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:purchaser_name, :item_description, :item_price, :purchase_count, :merchant_address, :merchant_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<%= form_for @cost, :html => { :class => "form-horizontal cost" } do |f| %>

    <% if @cost.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@cost.errors.count, "error") %> prohibited this cost from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @cost.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :purchaser_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :purchaser_name, :class => 'form-control' %>
    </div>
    <%= error_span(@cost[:purchaser_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :item_description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :item_description, :class => 'form-control' %>
    </div>
    <%= error_span(@cost[:item_description]) %>
  </div>
  <div class="control-group">
    <%= f.label :item_price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :item_price, :class => 'form-control' %>
    </div>
    <%= error_span(@cost[:item_price]) %>
  </div>
  <div class="control-group">
    <%= f.label :merchant_address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :merchant_address, :class => 'form-control' %>
    </div>
    <%= error_span(@cost[:merchant_address]) %>
  </div>
  <div class="control-group">
    <%= f.label :merchant_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :merchant_name, :class => 'form-control' %>
    </div>
    <%= error_span(@cost[:merchant_name]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            costs_path, :class => 'btn btn-default' %>

<% end %>

app/views/costs/edit.html.erb
<%- model_class = Cost -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/costs/index.html.erb
<%- model_class = Cost -%>
<!-- <div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <h4>Import Products</h4>
		<%= form_tag import_costs_path, multipart: true do %>
		  <%= file_field_tag :file %>
		  <%= submit_tag "Import" %>
		<% end %>
</div> -->

<% if params[:notice] %>
    <p id='notice'><%= params[:notice] %></p>
<% end %>

<% if params[:error] %>
    <p id='error'><%= params[:error] %></p>
<% end %>
<h3>Import Purchase Data</h3>
<%= form_tag data_importer_index_path, multipart: true do %>
    <%= file_field_tag :purchases_file %>
    <%= submit_tag 'Upload File' %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:purchaser_name) %></th>
      <th><%= model_class.human_attribute_name(:item_description) %></th>
      <th><%= model_class.human_attribute_name(:item_price) %></th>
      <th><%= model_class.human_attribute_name(:merchant_address) %></th>
      <th><%= model_class.human_attribute_name(:merchant_name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <td><%= link_to cost.id, cost_path(cost) %></td>
        <td><%= cost.purchaser_name %></td>
        <td><%= cost.item_description %></td>
        <td><%= cost.item_price %></td>
        <td><%= cost.merchant_address %></td>
        <td><%= cost.merchant_name %></td>
        <td><%=l cost.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cost_path(cost), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cost_path(cost),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cost_path,
            :class => 'btn btn-primary' %>

app/views/costs/new.html.erb
<%- model_class = Cost -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/costs/show.html.erb
<%- model_class = Cost -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:purchaser_name) %>:</strong></dt>
  <dd><%= @cost.purchaser_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:item_description) %>:</strong></dt>
  <dd><%= @cost.item_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:item_price) %>:</strong></dt>
  <dd><%= @cost.item_price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:merchant_address) %>:</strong></dt>
  <dd><%= @cost.merchant_address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:merchant_name) %>:</strong></dt>
  <dd><%= @cost.merchant_name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              costs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cost_path(@cost), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cost_path(@cost),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DataEngineering</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>